version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:test-machine
    command: sleep infinity
  test-machine:
    build:
      context: ./test-machine
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
