[package]
name = "authentik_sys"
version = "0.1.0"
edition = "2024"

[dependencies]
syslog = "7.0.0"
libc = "0.2.175"
log = "0.4.28"
serde = { version = "1.0.225", features = ["derive"] }
serde_yaml = "0.9.34"
prost = "0.12"
prost-types = "0.12"
tokio = "1.47.1"
tonic = "0.11"
tower = { version = "0.5.2", features = ["util" ]}
