[package]
name = "authentik_sys"
version = "0.1.0"
edition = "2024"

[dependencies]
syslog = "7.0.0"
libc = "0.2.174"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
prost = { version = "0.12" }
prost-types = { version = "0.12" }
tonic = { version = "0.11" }
tower = "0.5.2"
