name: "macOS Signing setup"
description: "Setup macOS Signing"

inputs:
  # bundle-id:
  #   required: true
  #   description: "Bundle ID of the project"
  p12-file-base64:
    description: ""
    required: true
  p12-password:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ inputs.p12-file-base64 }}
        p12-password: ${{ inputs.p12-password }}
    # - uses: apple-actions/download-provisioning-profiles@v4
    #   with:
    #     bundle-id: '${{ inputs.bundle-id }}'
    #     profile-type: 'MAC_APP_DEVELOPMENT'
    #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
    #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
    #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
