name: "macOS Signing setup"
description: "Setup macOS Signing"

inputs:
  bundle-id:
    required: true
    description: "Bundle ID of the project"

runs:
  using: composite
  steps:
    - uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
    - uses: apple-actions/download-provisioning-profiles@v4
      with:
        bundle-id: '${{ inputs.bundle-id }}'
        profile-type: 'MAC_APP_DEVELOPMENT'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
    - name: Build
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
