[package]
name = "authentik_pam"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "libpam-authentik authenticates users through authentik."

[lib]
name = "authentik_pam"
crate-type = ["cdylib"]

[dependencies]
authentik_sys = { path = "../utils_rs" }
authentik-client = "3.2025064.10"
base64 = "0.22.1"
ctor = "0.4.2"
hex = "0.4.3"
jsonwebtoken = "9.3.1"
jwks = "0.4.0"
libc = "0.2.174"
log = "0.4.27"
pam-bindings = "0.1.1"
prost = "0.12"
prost-types = "0.12"
rand = "0.9.2"
reqwest = { version = "0.12.22", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.142"
sha2 = "0.10.9"
tokio = "1.47.1"
tower = { version = "0.5.2", features = ["util" ]}

[package.metadata.deb]
name = "libpam-authentik"
maintainer = "Authentik Security Inc."
license-file = ["../LICENSE", "4"]
depends = [
    "libc6",
	"libssl3 | libssl3t64",
    "authentik-sysd",
    "libpam0g",
]
section = "security"
priority = "optional"
assets = [
    { source = "target/release/libauthentik_pam.so", dest = "usr/lib/security/pam_authentik.so", mode = "644"},
    { source = "debian/pam_config", dest = "usr/share/pam-configs/authentik", mode = "644"},
]
maintainer-scripts = "debian"
