name: build_rs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - pam
          - nss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ matrix.target }}/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('${{ matrix.target }}/**/Cargo.lock') }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y libpam0g-dev
      - run: make ${{ matrix.target }}/build
      - run: make ${{ matrix.target }}/package
      - uses: actions/upload-artifact@v4
        with:
          name: authentik_${{ matrix.target }}
          path: ${{ matrix.target }}/target/debian/*.deb
