name: build_js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target:
          - browser-ext
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: "${{ matrix.target }}/package.json"
          cache: "npm"
      - run: make ${{ matrix.target }}/package
      - uses: actions/upload-artifact@v4
        with:
          name: authentik_${{ matrix.target }}
          path: bin/
