name: build_go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target:
          - cli
          - agent
          - sysd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev
      - run: make ${{ matrix.target }}/package
      - uses: actions/upload-artifact@v4
        with:
          name: authentik_${{ matrix.target }}
          path: bin/
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev
      - uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5000s
