[package]
name = "authentik_nss"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "foo"

[lib]
name = "authentik_nss"
crate-type = ["cdylib"]

[dependencies]
ctor = "0.4.2"
hex = "0.4.3"
jsonwebtoken = "9.3.1"
jwks = "0.4.0"
libc = "0.2.174"
libnss = "0.9.0"
log = "0.4.27"
prost = { version = "0.12" }
prost-types = { version = "0.12" }
rand = "0.9.2"
reqwest = { version = "0.12.22", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.141"
serde_yaml = "0.9.34"
sha2 = "0.10.9"
syslog = "7.0.0"
tokio = "1.44.1"
tonic = { version = "0.11" }
tower = "0.5.2"

[package.metadata.deb]
name = "libnss-authentik"
maintainer = "Authentik Security Inc."
license-file = ["../LICENSE", "4"]
depends = [
    "libc6",
	"libssl3 | libssl3t64",
    "authentik-sys-agent",
]
section = "security"
priority = "optional"
assets = [
    { source = "target/release/libnss_authentik.so", dest = "usr/lib64/aarch64-linux-gnu/libnss_authentik.so.2", mode = "644"},
    { source = "target/release/libnss_authentik.so", dest = "usr/lib/aarch64-linux-gnu/libnss_authentik.so.2", mode = "644"},
]
maintainer-scripts = "debian"
